spring.application.name=Fincard
spring.datasource.url=jdbc:mysql://localhost:3306/fincard_db
spring.datasource.username=root
spring.datasource.password=@Sa26hil09
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Mail config for MailDev
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false


plaid.client-id=697cb3e67bae7c00219c6156
plaid.secret=387dd1f3796155274813321724e14f
plaid.env=sandbox